-- Seed sample supply directory entries for local/staging testing.
INSERT INTO "supply_directory_entries" (
  "id",
  "kind",
  "company_name",
  "contact_name",
  "email",
  "phone",
  "website",
  "region_slug",
  "notes",
  "is_active",
  "sort_order",
  "created_at",
  "updated_at"
) VALUES
  (
    'seed-dir-contractor-01',
    'contractor',
    'Bangkok Build Co.',
    'Somchai Prasert',
    'somchai@bangkokbuild.example',
    '+66 2 111 0001',
    'https://bangkokbuild.example',
    'bangkok',
    'General contractor — renovations and fit-outs',
    true,
    10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-contractor-02',
    'contractor',
    'Phuket Construction Ltd.',
    'Anya Wirat',
    'anya@phuketconstruction.example',
    '+66 76 222 0002',
    NULL,
    'phuket',
    'Villa and residential new builds',
    true,
    20,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-contractor-03',
    'contractor',
    'Chiang Mai Craft Works',
    'Nattapong Lee',
    'nattapong@cmcraft.example',
    '+66 53 333 0003',
    NULL,
    'chiang-mai',
    'Timber and finishing specialist',
    true,
    30,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-designer-01',
    'designer',
    'Andaman Design Studio',
    'Priya Somsak',
    'priya@andamandesign.example',
    '+66 2 444 0004',
    'https://andamandesign.example',
    'bangkok',
    'Architecture and permits for residential',
    true,
    10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-designer-02',
    'designer',
    'Lanna Architects',
    'Kritsada Moon',
    'kritsada@lannaarch.example',
    '+66 53 555 0005',
    NULL,
    'chiang-mai',
    'Design & permits — commercial interiors',
    true,
    20,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-supplier-01',
    'supplier',
    'Siam Materials Supply',
    'Wipada Chan',
    'wipada@siammaterials.example',
    '+66 2 666 0006',
    'https://siammaterials.example',
    'bangkok',
    'Cement, steel, tiles — nationwide delivery',
    true,
    10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-dir-supplier-02',
    'supplier',
    'Island MEP Parts',
    'Daniel Okada',
    'daniel@islandmep.example',
    '+66 76 777 0007',
    NULL,
    'phuket',
    'Electrical and HVAC components',
    true,
    20,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO NOTHING;
